### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by liuquanhao** [songtianyi/laosj#2]
liuxu:~$ go install github.com/songtianyi/laosj/cmds/laosj
go: downloading gopkg.in/mattn/go-colorable.v0 v0.1.2
go: downloading gopkg.in/mattn/go-isatty.v0 v0.0.8
build github.com/songtianyi/laosj/cmds/laosj: cannot load gopkg.in/mattn/go-colorable.v0: cannot find module providing package gopkg.in/mattn/go-colorable.v0

**Comment by songtianyi** [comment]
网络问题

**Comment by liuquanhao** [comment]
全中国都有这个网络问题吧。。怎么解决。。

**Comment by songtianyi** [comment]
google 一下 你就知道 :)

**Comment by liuquanhao** [comment]
实际上我在提问之前翻了google至少10页，查询了超过5个不同关键词。。

我还是直接用python吧

**Comment by songtianyi** [comment]
https://github.com/mattn/go-colorable
https://blog.csdn.net/liuliuzi_hz/article/details/52119575

用时不到一分钟 ：）

**Comment by songtianyi** [comment]
> 全中国都有这个网络问题吧。。怎么解决。。

既然你知道全中国都有这个问题，而全中国这么多gopher，那肯定有解决方案。你没在第一页的前几项里找到，就能猜到 是关键词不对。

**Comment by liuquanhao** [comment]
解决方案及友好回复：
https://www.v2ex.com/t/574000#reply34
