### ISSUE TITLE
meet "too many errors"

### ISSUE THREAD

**Issue by RUIZRUI** [songtianyi/laosj#3]
![截屏2020-01-05上午10 18 22](https://user-images.githubusercontent.com/43978293/71774169-dac97800-2fa4-11ea-820c-fc7625f574ea.png)

**Comment by songtianyi** [comment]
你的 github.com/urfave/cli 是什么版本。

**Comment by RUIZRUI** [comment]
> 你的 github.com/urfave/cli 是什么版本。

我放弃了，还是用Python爬吧，能力不够
